format = """
[](#d65d0e)\
$os\
$username\
[](bg:#d79921 fg:#d65d0e)\
$directory\
[](fg:#d79921 bg:#689d6a)\
$git_branch\
$git_status\
[](fg:#689d6a bg:#458588)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#458588 bg:#665c54)\
$docker_context\
[](fg:#665c54 bg:#3c3836)\
$time\
[ ](fg:#3c3836)\
"""

[username]
show_always = true
style_user = "bg:#d65d0e"
style_root = "bg:#d65d0e"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#d65d0e"
disabled = true # Disabled by default

[directory]
style = "bg:#d79921"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#458588"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#665c54"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#458588"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#458588"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#689d6a"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#689d6a"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#458588"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#458588"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#458588"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#458588"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#458588"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#458588"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#458588"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#458588"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#458588"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#3c3836"
format = '[ $time ]($style)'
